### ISSUE TITLE
Add use details for this software

### ISSUE THREAD

**Issue by ghost** [sonnym/clevo-xsm-wmi#1]
Hello!
Could be possible to add a guide or some information inside the Readme about how to use this software? How can I use it under Kubuntu, for example?

Thank you very much.

**Comment by tslpre** [comment]
Yes, it would be nice. I've tried to compile it in Lubuntu 15.04 and this is what I see:

# make

make -C /lib/modules/3.19.0-28-generic/build M=/home/stefano/Download/Clevo-Test/clevo-xsm-wmi-master/module modules
make[1]: Entering directory '/usr/src/linux-headers-3.19.0-28-generic'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/linux-headers-3.19.0-28-generic'

# make install

make -C /lib/modules/3.19.0-28-generic/build M=/home/stefano/Download/Clevo-Test/clevo-xsm-wmi-master/module modules_install
make[1]: Entering directory '/usr/src/linux-headers-3.19.0-28-generic'
  INSTALL /home/stefano/Download/Clevo-Test/clevo-xsm-wmi-master/module/clevo-xsm-wmi.ko
Can't read private key
  DEPMOD  3.19.0-28-generic
make[1]: Leaving directory '/usr/src/linux-headers-3.19.0-28-generic'

# depmod -a

# insmod clevo-xsm-wmi.ko

insmod: ERROR: could not insert module clevo-xsm-wmi.ko: No such device

dmesg says:
[ 9798.035196] clevo_xsm_wmi: Model Clevo P15xSM found
[ 9798.035259] clevo_xsm_wmi: Could not register WMI notify handler (0x0015)
[ 9798.035264] clevo_xsm_wmi: probe of clevo_xsm_wmi failed with error -5

**Comment by ghost** [comment]
It's great to see more people interested! I feel this project is abandoned. Let's hope!

**Comment by sonnym** [comment]
Sorry I never responded to your inquiry.  I am not the original author - I simply made a few changes to how the module works and mirrored it on github.  It looks like the upstream version (https://bitbucket.org/lynthium/clevo-xsm-wmi/) has my changes as well now.  Either way, I install the module with the following:

```
cd module
make
sudo cp clevo-xsm-wmi.ko /lib/modules/$(uname -r)/updates/
sudo insmod /lib/modules/$(uname -r)/updates/clevo-xsm-wmi.ko
```

Then you should be able to have it load automatically by adding `install clevo-xsm-wmi /sbin/modprobe wmi; /sbin/modprobe --ignore-install clevo-xsm-wmi` to `/etc/modprobe.d/99-local.conf` or a comparable file.
